echo "kubectl run nginx --image nginx --port=80 --dry-run=client -o yaml > pod.yaml"
echo "vim pod.yaml"

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: giropops
  name: giropops-2
spec:
  containers:
  - image: nginx
    name: giropops-2
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
